dependencies:
  flutter:
    sdk: flutter
  http: ^1.0.0
  json_annotation: ^4.8.0
  provider: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.7.0
